krush-env:
  destination:
    name: in-cluster
    namespace: dev

  applications:
    tulo:
      name: tulo
      path: chart
      repoURL: https://github.com/mrinalvirnave/krushapp-tulo.git
      targetRevision: HEAD
      valueFiles:
      - "../dev/values.yaml"
      values:
        heading: Tulo Override
        color: '#ffcc33'
        # sitePrefix: tulo-dev
        # text:
        #   - "is a"
        #   - "Maltese mix"  
    louie:
      path: chart
      repoURL: https://github.com/mrinalvirnave/krushapp-louie.git
      targetRevision: HEAD
      values:
        heading: Louie
        color: "lightgrey"
        sitePrefix: louie-dev
        text:
          - "is a"
          - "poodle mix"